---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-provider
spec:
  selector:
    matchLabels:
      app: hello-provider
  template:
    metadata:
      labels:
        app: hello-provider
    spec:
      containers:
      - name: hello-provider
        image: "gomesh/helloprovider:latest"
        imagePullPolicy: IfNotPresent
        env:
        - name: REGISTRY
          value: "http://service-center.servicecomb:30100"
        ports:
          - containerPort: 9080

---
apiVersion: v1
kind: Service
metadata:
  name: hello-provider
spec:
  selector:
    app: hello-provider
  ports:
  - protocol: TCP
    name: http
    port: 9080
    targetPort: 9080

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-consumer
spec:
  selector:
    matchLabels:
      app: hello-consumer
  template:
    metadata:
      annotations:
        sidecar.mesher.io/inject: "yes"
        sidecar.mesher.io/discoveryType: "sc"
      labels:
        app: hello-consumer
    spec:
      containers:
        - name: hello-consumer
          image: "gomesh/helloconsumer:latest"
          imagePullPolicy: IfNotPresent
          env:
          - name: TARGET
            value: hello-provider
          - name: http_proxy
            value: http://127.0.0.1:30101/
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: hello-consumer
spec:
  selector:
    app: hello-consumer
  ports:
  - protocol: TCP
    name: http
    port: 80
    nodePort: 30180
    targetPort: 80